config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "drones#index"

  resources :drones, only: [:index, :show, :new, :create] do
    resources :bookings, only: [:new, :create]
  end

  resources :dashboards, only: [:index], path: "dashboard"

  resources :bookings, only: [:edit, :update, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :drone

  validates :from_date, presence: true
  validates :to_date, presence: true
end

app/models/drone.rb
class Drone < ApplicationRecord
  has_one_attached :photo
  CATEGORY = %w[Racing Freestyle Cinematic Photography Other]

  belongs_to :user
  has_many :bookings

  validates :price, presence: true, numericality: true
  validates :brand, presence: true
  validates :model, presence: true
  validates :time_in_air, presence: true, numericality: true
  validates :description, presence: true
  validates :weight, presence: true, numericality: true
  validates :category, presence: true, inclusion: { in: CATEGORY }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bookings
  has_many :drones
  has_many :booked_drones, through: :bookings, source: :drone

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :address, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :address, :bank_details])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :address, :bank_details])
  end

  private

  # TODO: uncomment once dashboard is implemented
  # def after_sign_in_path_for(resource_or_scope)
  #   dashboard_path
  # end

  def after_sign_out_path_for(resource_or_scope)
    root_path
  end

  # TODO: uncomment once dashboard is implemented
  # def after_log_in_path_for(resource_or_scope)
  #   dashboard_path
  # end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new
    @drone = Drone.find(params[:drone_id])
  end

  def create
    @booking = Booking.new(booking_params)
    @drone = Drone.find(params[:drone_id])
    @booking.drone = @drone
    @booking.user = current_user
    if @booking.save
      redirect_to dashboards_path
    else
      render :new
    end
  end

  def edit
    @booking = Booking.find(params[:id])
    @drone = @booking.drone
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.update(accepted: params[:accepted])
    redirect_to dashboards_path, notice: 'Booking was successfully accepted.'
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.delete

    redirect_to dashboards_path
  end

  private

  def booking_params
    params.require(:booking).permit(:from_date, :to_date, :accepted)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
    @user = current_user

    @my_requests = Booking.where(drone: Drone.where(user: @user))
    @my_drones = Drone.where(user: @user)
    @my_bookings = Booking.where(user: @user)
  end
end

app/controllers/drones_controller.rb
class DronesController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
    @drones = Drone.all
    filter_drones
  end

  def show
    @drone = Drone.find(params[:id])
    @drones = Drone.all
    @same_category_drones = @drones.where(category: Drone.find(params[:id]).category)
  end

  def new
    @drone = Drone.new
  end

  def create
    @drone = Drone.new(drone_params)
    @drone.user = current_user
    if @drone.save!
      redirect_to dashboards_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def drone_params
    params.require(:drone).permit(:price, :brand, :model, :time_in_air, :description, :weight, :category, :availability, :photo)
  end

  def filter_drones
    @drones = Drone.all
    @drones = @drones.where("category ILIKE :query OR price ILIKE :query", query: "%#{params[:query]}%") if params[:query].present?
    @drones = @drones.where(category: params[:category]) if params[:category].present?
    @drones = @drones.where("price >= ?", params[:min_price]) if params[:min_price].present?
    @drones = @drones.where("price <= ?", params[:max_price]) if params[:max_price].present?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<%#-- update booking --%>
<div class="bg-black d-flex align-objects-center">
  <div class="container h-100">
      <div class="card rounded-4 bg-dark bg-opacity-50 text-secondary my-4">
        <div class="d-flex justify-content-center align-items-center h-50">
                   <% if drone.photo.attached? %>
                     <%= cl_image_tag drone.photo.key, crop: :fill, class: "rounded-4 w-100 h-100" %>
                   <% else %>
                     <img src="https://dji-official-fe.djicdn.com/cms/uploads/ae5d8b9987be8d5ecdeb5d502a1e887c.png" alt="<%= drone.model %>" class="w-100">
                   <% end %>
        </div>
        <div class="px-3">
          <h2 class="my-3"><%= @drone.model %></h2>
          <div class="my-3">
            <%= simple_form_for [@booking] do |f| %>
              <%= f.input :from_date, as: :string, input_html: { data: { controller: "datepicker" } }  %>
              <%= f.input :to_date, as: :string, input_html: { data: { controller: "datepicker" } }   %>
              <div class="btn btn-primary"><%= f.button :submit %></div>
            <% end %>
          </div>
        </div>
    </div>
  </div>
</div>

app/views/bookings/new.html.erb
<%#-- new booking --%>
<div class="background-black-gradient h-100 ">
  <div class="container d-flex flex-column rounded-4 bg-dark bg-opacity-50 text-secondary p-2 my-5">
    <div class="d-flex flex-row text-secondary p-3">

      <div class="col-6 mx-auto">
       <% if @drone.photo.attached? %>
         <%= cl_image_tag @drone.photo.key, crop: :fill, class: "rounded-4 w-100 h-100" %>
       <% else %>
         <img src="https://dji-official-fe.djicdn.com/cms/uploads/ae5d8b9987be8d5ecdeb5d502a1e887c.png" alt="<%= drone.model %>" class="w-100">
       <% end %>
      </div>

      <div class="card col-6 text-white bg-dark bg-opacity-50 p-2">
        <div class="card-body d-flex flex-column text-start">
          <h1>Book <%= @drone.model %></h1>
          <%= simple_form_for [@drone, @booking], defaults: {label: false}, html: { class: "flex-grow-1 text-secondary"} do |f| %>
            <div class="h-100 d-flex flex-column">
              <div>
                <div class="my-2"><%= f.label :from_date, "FROM:" %></div>
                <%= f.input :from_date, as: :string, input_html: { data: { controller: "datepicker" }, placeholder: Date.today.strftime('%Y-%m-%d'), style: 'background-color: #292929;', class: 'placeholder-text' } %>
                <div class="mt-4 mb-2"><%= f.label :from_date, "TO:" %></div>
                <%= f.input :to_date, as: :string, input_html: { data: { controller: "datepicker" }, placeholder: Date.today.strftime('%Y-%m-%d'), style: 'background-color: #292929;', class: 'placeholder-text' } %>
              </div>
              <div class="mt-auto">
                <%= f.submit 'Book', class: "btn w-100 rounded-4 btn-light p-2" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/dashboards/index.html.erb
<body class="background-black-gradient">
  <div class="container">
    <h2 class="text-center mb-5">My Dashboard</h2>

    <!-- MY BOOKINGS -->
    <div class="mb-5">
      <h4 class="py-2 text-light">Upcoming Bookings</h4>
      <div class="row bg-dark rounded-4">
        <% @my_bookings.to_a.sort!{ |a, b| a.from_date <=> b.from_date }.each do |booking| %>
          <div class="col-3 mt-2">
            <div class="card h-100 rounded-4 text-secondary bg-dark border-0">
              <div class="card-body">
                <div class="bg-secondary bg-opacity-50 rounded-4 mb-3 h-50">
                   <% if booking.drone.photo.attached? %>
                     <%= cl_image_tag booking.drone.photo.key, crop: :fill, class: "rounded-4 w-100 h-100" %>
                   <% else %>
                     <img src="https://dji-official-fe.djicdn.com/cms/uploads/ae5d8b9987be8d5ecdeb5d502a1e887c.png" alt="<%= booking.drone.model %>" class="w-100">
                   <% end %>
                </div>
                <h5 class="card-title"><%= booking.drone.model %></h5>
                <div class="card-text">
                  <div><strong>From: </strong> <%= booking.from_date.strftime('%Y-%m-%d') %></div>
                  <div><strong>To: </strong><%= booking.to_date.strftime('%Y-%m-%d') %></div>
                  <div class="pt-2 mb-2"><%=
                    if booking.accepted
                      "Confirmed"
                    else
                      "Waiting for confirmation"
                    end
                  %></div>
                </div>
              </div>
            </div>
          </div>
        <% end %>

        <% if @my_bookings.empty? %>
          <div class="col-3 mt-2">
            <div class="card rounded-4 text-secondary bg-dark border-0 mb-0">
              <div class="card-body m-0 px-2 pb-0 pt-2">
                <div class="bg-secondary bg-opacity-25 rounded-4 mb-3">
                  <div style="height: 275px;" class="d-flex justify-content-center align-items-center">
                    <div class="">No bookings yet</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>

      </div>
    </div>
    <!-- MY BOOKINGS -->

    <!-- BOOKING REQUESTS -->
    <div class="mb-5">
      <h4 class="py-2 text-light">Bookings for my Drones</h4>
      <div class="row bg-dark p-0 rounded-4">

        <% @my_requests.to_a.sort!{ |a, b| a.from_date <=> b.from_date }.each do |booking|%>
          <div class="col-3 my-2">
            <div class="card-body m-0 px-2 pb-0 pt-2 h-100 rounded-4 text-secondary bg-dark border-0">
              <div class="card-body">
                <div class="bg-secondary bg-opacity-50 rounded-4 mb-3 h-75">
                   <% if booking.drone.photo.attached? %>
                     <%= cl_image_tag booking.drone.photo.key, crop: :fill, class: "rounded-4 w-100 h-100" %>
                   <% else %>
                     <img src="https://dji-official-fe.djicdn.com/cms/uploads/ae5d8b9987be8d5ecdeb5d502a1e887c.png" alt="<%= drone.model %>" class="w-100">
                   <% end %>
                </div>
                <h5 class="card-title"><%= booking.drone.model %></h5>
                <div class="card-text d-flex flex-column">
                  <div><strong>Request from: </strong> <%= booking.user.first_name %> <%= booking.user.last_name %></div>
                  <div><strong>From: </strong> <%= booking.from_date.strftime('%Y-%m-%d') %></div>
                  <div><strong>To: </strong><%= booking.to_date.strftime('%Y-%m-%d') %></div>
                </div>
                <p>
                Total: <%= ((booking.to_date.to_date - booking.from_date.to_date).to_i * booking.drone.price) %>0 €
                <div class="d-flex flex-row">
                  <% if booking.accepted%>
                    <%= link_to booking_path(booking), data: {turbo_method: :delete} do %>
                      <div class="text-danger">Cancel Booking</div>
                    <% end %>
                  <% else %>
                    <%= link_to booking_path(booking, accepted: true), data: {turbo_method: :patch} do %>
                      <div class="text-success">Accept</div>
                    <% end %>
                    <%= link_to booking_path(booking), data: {turbo_method: :delete} do %>
                      <div class="text-danger mx-2">Decline</div>
                    <% end %>
                  <% end %>
                </div>
              </p>
              </div>
            </div>
          </div>
        <% end%>

        <% if @my_requests.empty? %>
          <div class="col-3 mt-2">
            <div class="card rounded-4 text-secondary bg-dark border-0 mb-0">
              <div class="card-body m-0 px-2 pb-0 pt-2">
                <div class="bg-secondary bg-opacity-25 rounded-4 mb-3">
                  <div style="height: 275px;" class="d-flex justify-content-center align-items-center">
                    <div class="">No drones booked</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>

      </div>
    </div>
    <!-- BOOKING REQUESTS -->

    <!-- MY DRONES -->
    <div class="mb-5">
      <h4 class="py-2 text-light">My Drones</h4>

      <div class="row bg-dark rounded-4">
        <% @my_drones.each do |drone| %>
          <div class="col-3 my-2">
            <div class="card h-100 rounded-4 text-secondary bg-dark border-0">
              <div class="card-body">
                <div class="bg-secondary bg-opacity-50 rounded-4 mb-3 h-75">
                   <% if drone.photo.attached? %>
                     <%= cl_image_tag drone.photo.key, crop: :fill, class: "rounded-4 w-100 h-100" %>
                   <% else %>
                     <img src="https://res.cloudinary.com/dmlxmpwua/image/upload/v1706870994/Drone_5_suu3hb.jpg" alt="<%= drone.model %>" class="w-100" style="object-fit: cover">
                   <% end %>
                </div>
                <h5 class="card-title"><%= drone.model %></h5>
                <div class="card-text">
                  <%= drone.brand %><br>
                </div>
              </div>
            </div>
          </div>
        <% end %>

        <div class="col-3 my-2">
          <div class="card rounded-4 text-secondary bg-dark border-0">
            <div class="card-body">
              <div class="bg-secondary bg-opacity-25 rounded-4 mb-2">
                <%= link_to new_drone_path do %>
                  <div style="height: 295px;" class="d-flex justify-content-center align-items-center">
                    <div class="display-1">+</div>
                  </div>
                <% end %>
              </div>
                <h5 class="card-title invisible">Add a new drone</h5>
                <div class="card-text">
                  <%=  %><br>
                </div>
            </div>
          </div>
        </div>

      </div>
    </div>
    <!-- MY DRONES -->

  </div>
</body>

app/views/drones/index.html.erb
<body class="background-black-gradient">

  <div class="banner">
    <div class="container">
      <div class="d-flex flex-column">
        <h1>Seamless Aerial Solutions.</h1>
        <%# <p>Explore the skies effortlessly</p> %>
      </div>
    </div>
  </div>

  <div class="container  search">
    <div class="row justify-content-center">
      <div class="col-sm-8 mt-2">
        <%= form_with(method: :get, class: "d-flex") do |form| %>
            <div class="input-group">
              <%= select_tag :category,
                    options_for_select(Drone.distinct.pluck(:category).compact, params[:category]),
                    include_blank: "Category",
                    class: "form-control"
                %>
            </div>
            <div class="input-group">
              <%= text_field_tag :min_price,
                    params[:min_price],
                    placeholder: "Min Price",
                    class: "form-control"
                %>
            </div>
            <div class="input-group">
              <%= text_field_tag :max_price,
                    params[:max_price],
                    placeholder: "Max Price",
                    class: "form-control"
                %>
            </div>
            <div class="input-group-append">
              <button type="submit" class="btn btn-secondary">
                <img src="<%= asset_path('search.svg') %>" alt="Search">
              </button>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <% @drones.each do |drone| %>
        <div class="col-3 my-2">
          <%= link_to(drone_path(drone)) do %>
           <div class="d-flex flex-column h-100 rounded-4 bg-dark bg-opacity-50 text-secondary p-3">
             <div class="h-50">
                   <% if drone.photo.attached? %>
                     <%= cl_image_tag drone.photo.key, class: "rounded-4 w-100 h-100 object-fit-cover" %>
                   <% else %>
                     <img src="https://dji-official-fe.djicdn.com/cms/uploads/ae5d8b9987be8d5ecdeb5d502a1e887c.png" alt="<%= drone.model %>" class="w-100">
                   <% end %>
             </div>
             <div><h2 class="card-title mt-3"><%= drone.model %></h2></div>
             <div class="d-flex flex-column flex-grow-1 align-content-between flex-wrap">
               <p><%= drone.description %></p>
               <p class="mt-auto"><%= drone.price %>0 €/day</p>
               <!-- Add more drone details here -->
             </div>
           </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</body>

app/views/drones/new.html.erb
<div class="background-black-gradient h-100 d-flex align-objects-center">
  <div class="container d-flex flex-column rounded-4 bg-dark bg-opacity-50 text-secondary p-2 my-5">
    <div class="d-flex flex-row text-secondary p-3">

      <div class="col-6 my-auto">
                   <% if @drone.photo.attached? %>
                     <%= cl_image_tag drone.photo.key, crop: :fill, class: "rounded-4 w-100 h-100" %>
                   <% else %>
                     <img src="https://dji-official-fe.djicdn.com/cms/uploads/ae5d8b9987be8d5ecdeb5d502a1e887c.png" alt="<%= @drone.model %>" class="w-100">
                   <% end %>
      </div>

      <div class="card col-6 text-white bg-dark bg-opacity-50 p-2">
        <div class="card-body d-flex flex-column text-start">
          <h1>Add a new drone</h1>
          <%= simple_form_for [@user, @drone], defaults: {label: false}, html: { class: "flex-grow-1 text-secondary"} do |f| %>
            <div class="h-100 d-flex flex-column">
              <div>
                <div class="my-2"><%= f.label :brand, "BRAND:" %></div>
                <%= f.input :brand, input_html: { placeholder: "brand name", class: 'placeholder-text', style: 'background-color: #292929; color: #ffffff;' } %>
                <div class="my-2"><%= f.label :model, "MODEL:" %></div>
                <%= f.input :model, input_html: { placeholder: "Nimbus 3000", class: 'placeholder-text', style: 'background-color: #292929; color: #ffffff;' }  %>
                <div class="my-2"><%= f.label :price, "PRICE PER DAY:" %></div>
                <%= f.input :price, input_html: { placeholder: "30 €", class: 'placeholder-text', style: 'background-color: #292929; color: #ffffff;' } %>
                <div class="my-2"><%= f.label :time_in_air, "TIME IN AIR:" %></div>
                <%= f.input :time_in_air, input_html: { placeholder: "45 min", class: 'placeholder-text', style: 'background-color: #292929; color: #ffffff;' }  %>
                <div class="my-2"><%= f.label :description, "DESCRIPTION:" %></div>
                <%= f.input :description, input_html: { placeholder: "Fast drone with great camera capabilities", class: 'placeholder-text', style: 'background-color: #292929; color: #ffffff;' }  %>
                <div class="my-2"><%= f.label :weight, "WEIGHT:" %></div>
                <%= f.input :weight, input_html: { placeholder: "450 g", class: 'placeholder-text', style: 'background-color: #292929; color: #ffffff;' }  %>
                <div class="my-2"><%= f.label :category, "CATEGORY:" %></div>
                <%= f.input :category, collection: Drone::CATEGORY, input_html: { placeholder: "category", class: 'btn rounded-5 text-light text-start placeholder-text', style: 'background-color: #292929; height: 50px; color: #ffffff;' } %>
                <div class="my-2"><%= f.label :photo, "IMG:" %></div>
                <%= f.input :photo, as: :file, input_html: {placeholder: "Your File", class: 'placeholder-text'}   %>
              </div>
              <div class="mt-auto">
                <%= f.submit 'Add', class: "btn w-100 rounded-5 btn-light p-2 mt-3", input_html: { style: 'height: 50px;' } %>
              </div>
            </div>
          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/drones/show.html.erb
<div class="background-black-gradient">
  <div class="container d-flex flex-column rounded-4 bg-dark bg-opacity-50 text-secondary p-2 my-5">
    <%#-- drone card --%>
      <div class="d-flex flex-row text-secondary p-3">
        <div class="col-6 mx-auto">
           <% if @drone.photo.attached? %>
              <%= cl_image_tag @drone.photo.key, class: "rounded-4 w-100 h-100", style: "object-fit: cover;" %>
           <% else %>
              <img class="img-fluid" src="https://dji-official-fe.djicdn.com/cms/uploads/ae5d8b9987be8d5ecdeb5d502a1e887c.png" alt="Drone Picture" width="100%">
           <% end %>
        </div>

        <div class="card col-6 text-white bg-dark bg-opacity-50 mx-2 mb-0">
          <div class="card-body text-start">
            <h1 class=""><%= @drone.model %></h1>
            <p class="card-text mt-3"><div class="text-uppercase font-weight-bold">Brand</div> <%= @drone.brand %></p>
            <p class="card-text"><div class="text-uppercase font-weight-bold">Description</div> <%= @drone.description %></p>
            <p class="card-text"><div class="text-uppercase font-weight-bold">Price</div> <%= @drone.price %>0 €/day</p>
            <p class="card-text"><div class="text-uppercase font-weight-bold">Flying Time</div> <%= @drone.time_in_air %> min</p>
            <p class="card-text"><div class="text-uppercase font-weight-bold">Weight</div> <%= @drone.weight %> g</p>
            <p class="card-text "><div class="text-uppercase font-weight-bold">Category</div> <%= @drone.category %></p>
          </div>
          <%= link_to new_drone_booking_path(@drone), class: "btn rounded-4 btn-light p-2 m-2" do %>
            Book
          <% end %>
        </div>
    </div>
  </div>
        <%# add suggestions %>
  <div class="container">
    <h2>We think you may also like</h2>
    <h6>Category <span><%= @drone.category %></span></h6>
    <div class="row my-3">
      <% @same_category_drones.limit(4).each do |drone| %>
        <div class="col-3 my-2">
          <%= link_to(drone_path(drone)) do %>
           <div class="d-flex flex-column h-100 rounded-4 bg-dark bg-opacity-50 text-secondary p-2">
             <div class="h-50">
           <% if drone.photo.attached? %>
              <%= cl_image_tag drone.photo.key, crop: :fill, class: "rounded-4 w-100 h-100" %>
           <% else %>
              <img class="img-fluid" src="https://dji-official-fe.djicdn.com/cms/uploads/ae5d8b9987be8d5ecdeb5d502a1e887c.png" alt="Drone Picture" width="100%">
           <% end %>
             </div>
             <div><h2 class="mt-2"><%= drone.model %></h2></div>
             <div class="d-flex flex-grow-1 align-content-between flex-wrap">
               <p><%= drone.description %></p>
               <p><%= drone.price %>0 €/day</p>
               <!-- Add more drone details here -->
             </div>
           </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SkyHighRentals</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%# Flatpicker %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= javascript_importmap_tags %>

  </head>

  <body>
    <div class="pages-container">
      <%= render "shared/flashes" %>
      <%= render "shared/navbar" %>
      <div>
        <%= yield %>
      </div>
      <p class="notice m-0 p-0"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= render "shared/footer" %>
    </div>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
  <footer class="bg-dark text-light">
    <div class="container text-center mb-0 p-2">
      <p class="mb-0 text-tiny">&copy; 2024 Sky High Rentals - All rights reserved. Developed by QuickQuizz Inc.</p>
    </div>
  </footer>

app/views/shared/_navbar.html.erb
  <div class="navbar justify-content-between bg-black">
    <div class="d-flex flex-row">
      <a href="">
        <%= link_to root_path, class: "p-0 d-flex" do %>
          <img class="navbar-brand" src="https://st3.depositphotos.com/27269280/36592/v/450/depositphotos_365929444-stock-illustration-drone-logo-concept-design-arial.jpg" alt="Drone logo" height="70px">
          <span class="align-self-center navbar-link">Sky High</span>
        <% end %>
      </a>
    </div>
    <div class="links mx-4">
      <% if user_signed_in? %>
        <span class="mx-2"><%= link_to "Dashboard", dashboards_path %></span>
        <%# div href="#" class="navbar-link">Contact</a> TODO: uncomment if implemented to lead somewhere %>
        <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "navbar-link" %>
      <% else %>
        <%= link_to "Log In", new_user_session_path, class: "navbar-link" %>
      <% end %>
  </div>
</div>